# Generated by Django 2.2.6 on 2020-05-06 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpassword', models.CharField(max_length=20, verbose_name='oldpassword')),
                ('newpassword', models.CharField(max_length=20, verbose_name='newpassword')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('owner4', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Departments')),
                ('owner6', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner6', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Meal_Categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
                ('owner2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='surname')),
                ('login', models.CharField(max_length=20, verbose_name='login')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.PositiveIntegerField(verbose_name='phone')),
                ('owner5', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner5', to=settings.AUTH_USER_MODEL)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Roles')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
                ('owner7', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner7', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Statuses', to='million.Statuses')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isitopen', models.BooleanField(verbose_name='isitopen')),
                ('date', models.DateTimeField(verbose_name=True)),
                ('meals', models.ManyToManyField(to='million.Meals')),
                ('tableid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Table')),
                ('waiterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meals_to_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', models.ManyToManyField(to='million.Meals')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Get_User_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, verbose_name='token')),
                ('owner3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner3', to=settings.AUTH_USER_MODEL)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Roles', to='million.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20, verbose_name='date')),
                ('servicefee', models.PositiveIntegerField(verbose_name='servicefee')),
                ('totalsum', models.PositiveIntegerField(verbose_name='totalsum')),
                ('meals', models.ManyToManyField(to='million.Meals')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Orders')),
            ],
        ),
    ]
