# Generated by Django 2.2.6 on 2020-05-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checks',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='checks',
            name='totalsum',
        ),
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('done', 'done')], max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='MealsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Meals', verbose_name='Name')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealsid', to='million.Orders')),
            ],
        ),
        migrations.AddField(
            model_name='checks',
            name='mealsid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='million.MealsCount', verbose_name='Meal'),
            preserve_default=False,
        ),
    ]
