# Generated by Django 2.2.6 on 2020-05-10 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0003_auto_20200511_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='owner4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='get_user_token',
            name='owner3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal_categories',
            name='owner6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meals',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='table',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='owner5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner5', to=settings.AUTH_USER_MODEL),
        ),
    ]
