# Generated by Django 2.2.6 on 2020-05-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0004_auto_20200511_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='meals',
        ),
    ]
