# Generated by Django 2.2.6 on 2020-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0005_remove_orders_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='meals',
            field=models.ManyToManyField(to='million.Meals'),
        ),
    ]
