# Generated by Django 2.2.6 on 2019-12-18 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('million', '0006_auto_20191203_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='users',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
