# Generated by Django 2.2.6 on 2020-05-10 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0006_orders_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='owner7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner7', to=settings.AUTH_USER_MODEL),
        ),
    ]
