# Generated by Django 2.2.6 on 2020-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0007_auto_20200511_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='servicefee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='servicefee'),
        ),
    ]
