# Generated by Django 2.2.6 on 2020-05-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0008_auto_20200516_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='mealsid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='million.MealsCount', verbose_name='Meal'),
        ),
    ]
