# Generated by Django 2.2.6 on 2020-03-31 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('million', '0008_auto_20191219_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpassword', models.CharField(default='', max_length=20, verbose_name='oldpassword')),
                ('newpassword', models.CharField(default='', max_length=20, verbose_name='newpassword')),
            ],
        ),
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='servicepercentage',
            name='percentage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Statuses', to='million.Statuses'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isitopen', models.BooleanField(default='', verbose_name='isitopen')),
                ('date', models.DateTimeField(verbose_name=True)),
                ('meals', models.ManyToManyField(to='million.Meals')),
                ('tableid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Table')),
                ('waiterid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meals_to_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', models.ManyToManyField(to='million.Meals')),
                ('orderid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Get_User_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=20, verbose_name='token')),
                ('roleid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Roles', to='million.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='', max_length=20, verbose_name='date')),
                ('servicefee', models.PositiveIntegerField(default='', verbose_name='servicefee')),
                ('totalsum', models.PositiveIntegerField(default='', verbose_name='totalsum')),
                ('meals', models.ManyToManyField(to='million.Meals')),
                ('orderid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Orders')),
            ],
        ),
    ]
