# Generated by Django 2.2.6 on 2020-03-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0009_auto_20200331_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
