# Generated by Django 2.2.6 on 2020-04-23 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0010_auto_20200331_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_password',
            name='newpassword',
            field=models.CharField(max_length=20, verbose_name='newpassword'),
        ),
        migrations.AlterField(
            model_name='change_password',
            name='oldpassword',
            field=models.CharField(max_length=20, verbose_name='oldpassword'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='date',
            field=models.DateField(max_length=20, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Orders'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='servicefee',
            field=models.PositiveIntegerField(verbose_name='servicefee'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='totalsum',
            field=models.PositiveIntegerField(verbose_name='totalsum'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='get_user_token',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Roles', to='million.Roles'),
        ),
        migrations.AlterField(
            model_name='get_user_token',
            name='token',
            field=models.CharField(max_length=20, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='meal_categories',
            name='departmentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Departments'),
        ),
        migrations.AlterField(
            model_name='meal_categories',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Meal_Categories'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meals',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='meals_to_order',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='isitopen',
            field=models.BooleanField(verbose_name='isitopen'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tableid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Table'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='waiterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicepercentage',
            name='percentage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Statuses', to='million.Statuses'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=20, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=20, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='users',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Roles'),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='surname'),
        ),
    ]
