# Generated by Django 2.2.6 on 2020-04-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0011_auto_20200423_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='owner',
        ),
        migrations.AddField(
            model_name='users',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
