# Generated by Django 2.2.6 on 2020-04-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
